# input
path_to_mlflow: ???
experiment_id: ???
discriminators: # in the format -> run_id: ['curve_type_1', 'curve_type_2', ...]
  fb57a260e56945cb8f8b1e11cb2bfbae : ['roc_curve']
  528a5e4391c143fdad06451e8bf98a0e : ['roc_curve']
  997f18c9924c409eb80c1b7b757c127a : ['roc_curve']
reference:
  fb57a260e56945cb8f8b1e11cb2bfbae : 'roc_curve'


# region
vs_type: jet # jet/e/mu/tau
dataset_alias: ??? # sample alias asigned in yaml cfg at eval step
pt_bin: ??? # list, e.g [20, 100], min and max
eta_bin: ??? # list, e.g [0, 1.5], min and max (of absolute eta)
L_bin: ???

# will log the plot to the run of the first discriminator in the "discriminators" list
output_name: 'roc_curve_vs_${vs_type}_${dataset_alias}_pt_${pt_bin[0]}_${pt_bin[1]}_eta_${eta_bin[0]}_${eta_bin[1]}_L_${L_bin[0]}_${L_bin[1]}_${L_bin[2]}_${L_bin[3]}'
