# input
path_to_mlflow: ???
experiment_id: ???
discriminators: # in the format -> run_id: ['curve_type_1', 'curve_type_2', ...]
  84943ef984c24f5281206f8861cd64a7 : ['roc_curve']
  2429b37680c9449a9520dd9995b18352 : ['roc_curve']
  84c706f05c7c4a15bbcb90dc241026d6 : ['roc_curve']
  aa234384bf5040929163e2da76c71bae : ['roc_curve']
reference:
  aa234384bf5040929163e2da76c71bae : 'roc_curve'


# region
vs_type: jet # jet/e/mu/tau
dataset_alias: ??? # sample alias asigned in yaml cfg at eval step
pt_bin: ??? # list, e.g [20, 100], min and max
eta_bin: ??? # list, e.g [0, 1.5], min and max (of absolute eta)
L_bin: ???

# will log the plot to the run of the first discriminator in the "discriminators" list
output_name: 'roc_curve_vs_${vs_type}_${dataset_alias}_pt_${pt_bin[0]}_${pt_bin[1]}_eta_${eta_bin[0]}_${eta_bin[1]}_L_${L_bin[0]}_${L_bin[1]}'
