# basic imports
defaults:
  - discriminator: DisTauTag_v1
  - plot_setup
  - _self_

# mflow run info
path_to_mlflow: ???
experiment_id: ???
run_id: ???

# phase space region
period: '2018 (13 TeV)'
vs_type: "jet" # jet/e/mu
dataset_alias: ALL_DATA # alias to reference a mixture of input_samples below, e.g. tau_DY_jet_TT
pt_bins: [[20, 100], [100, 1000]]
eta_bins: [[0, 2.4]]

# selection
input_branches: [ 'jet_pt', 'jet_eta' ] # add here branches with targets/prediction if necessary
cuts: "jet_pt>20"

# inputs/paths
input_samples: # "sample_alias": [list of strings with tau types to be selected]
  ShuffleMergeTest: ['tau',"${vs_type}"]

path_to_input: null
path_to_pred: '${path_to_mlflow}/${experiment_id}/${run_id}/artifacts/predictions/{sample_alias}/*_pred.h5'
path_to_target: '${path_to_mlflow}/${experiment_id}/${run_id}/artifacts/predictions/{sample_alias}/*_pred.h5'
path_to_weights_taus: null
path_to_weights_vs_type: null
