# basic imports
defaults:
  - discriminator: ???
  - plot_setup
  - _self_

# mflow run info
path_to_mlflow: ???
experiment_id: ???
run_id: ???

# phase space region
period: '2018 (13 TeV)'
vs_type: "jet" # jet/e/mu
dataset_alias: ??? # alias to reference a mixture of input_samples below, e.g. tau_DY_jet_TT
pt_bins: [[20, 100], [100, 1000]]
eta_bins: [[0, 2.4]]
Lxy_bins: [[0.0, 1.0], [1.0, 10.0], [10.0, 30.0], [30.0, 50.0]]

# selection
input_branches: [ 'jet_pt', 'jet_eta', 'Lxy', 'Lz' ] # add here branches with targets/prediction if necessary
cuts: "jet_pt>20"

# inputs/paths
input_samples: # "sample_alias": [list of strings with tau types to be selected]
  STAU_M100_10cm : ['tau']
  TTTOSemiLeptonic : ['jet']

path_to_input: null
path_to_pred: '${path_to_mlflow}/${experiment_id}/${run_id}/artifacts/predictions/{sample_alias}/*_pred.h5'
path_to_target: '${path_to_mlflow}/${experiment_id}/${run_id}/artifacts/predictions/{sample_alias}/*_pred.h5'
path_to_weights_taus: null
path_to_weights_vs_type: null
